title: Trey Dolan
author: 
  name: Trey Dolan
theme: minima

minima:
  skin: classic

header_pages:
  - index.md
  - projects.md
  - about.md
  - contact.md


footer_text: >
  Web Developer | JavaScript, WordPress, Networking Labs