title: Trey Dolan
author: 
  name: Trey Dolan
description: "Web Developer | JavaScript, WordPress, Networking Labs"
theme: minima

minima:
  skin: classic

header_pages:
  - index.md
  - projects.md
  - about.md
  - contact.md
