title: Trey Dolan

description: "Web Developer | JavaScript, WordPress, Networking Labs"
theme: minima

author:
  name: Trey Dolan

minima:
  skin: classic

header_pages:
  - index.md
  - projects.md
  - about.md
  - contact.md
